### ISSUE TITLE
MacOS 14.1 m1无法运行

### ISSUE THREAD

**Issue by lable** [Air-duino/AirISP#17]
### 描述一下这个bug / Describe the bug

MacOS 14.1 m1无法运行

### 复现步骤 / To Reproduce

MacOS 14.1 m1无法运行

### 预期的行为 / Expected behavior

替换成AirISP-osx-x64.tar可以正常下载

### 系统 / System

MacOS 14.1/m1

### 软件版本 / Version

1.2.8.0

### 验证

- [x] 检查该问题是否已被提过 / Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [ ] 提供了最小可复现工程或详细的复现步骤，确保开发者可以复现 / The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HalfSweet** [comment]
.net上游的bug，已解决（虽然不知道是什么时候解决的

**Comment by wang-yupu** [comment]
1.2.8.0依然是arm64无法运行，arduino ide显示是signal:killed 直接执行airisp是zsh:killed
amd64可以正常运行，解决了个鬼喔

**Comment by chenxuuu** [comment]
无mac arm处理器测试环境，你可以自己编译试试
